### ISSUE TITLE
Notifications issue

### ISSUE THREAD

**Issue by JamalZafar1** [crazyhitty/firebase-chat#1]
When sender send message, receiver doesn't receive the notification. Kindly help me

**Comment by crazyhitty** [comment]
Yeah, someone previously also mentioned this issue to me via mail, will check it out as soon as I get some time on my hands.

**Comment by JamalZafar1** [comment]
Kindly do it as quick as possible, I have to use this in my project. Will be very thankful to u. Waiting!

**Comment by JamalZafar1** [comment]
Kindly tell me will you solve this issue?

**Comment by crazyhitty** [comment]
Hi @nowantednameisavailabel , I just checked the project. Notifications are working for me. Make sure to put valid server API key in [FcmNotificationBuilder](https://github.com/crazyhitty/firebase-chat/blob/master/app/src/main/java/com/crazyhitty/chdev/ks/firebasechat/fcm/FcmNotificationBuilder.java#L27) class.

You can find your API key here: 
![](http://i.imgur.com/3XjnI3t.png)

**Comment by JamalZafar1** [comment]
Thanks a lot, its working now.
