### ISSUE TITLE
Unable to open the tutorial link and also the app in Android studio

### ISSUE THREAD

**Issue by abhishekds94** [crazyhitty/firebase-chat#10]
Hey,
I'm unable to open the app in AS it says some files are missing from the directory. May I know how to build the directory and the DB structure?
Can you provide me any tutorial kind of reference for the same?

**Comment by crazyhitty** [comment]
@Abhishekds94 Sorry, my website is down currently, that is why tutorial link was not working. So now I have added the entire tutorial in [README.md](https://github.com/crazyhitty/firebase-chat/blob/master/README.md) file of the project. Have a great day!
