### ISSUE TITLE
FirebaseMessagingService Never Called either app in foreground or background, No notification received for messages sent when app closed

### ISSUE THREAD

**Issue by curiousmit** [crazyhitty/firebase-chat#7]
The FirebaseMessaging service is not working and onMessageReceived is never called regardless of app in background or foreground. Due to this the notification is also not working. Tried putting log for data received in onMessageReceived, but no logs came, which indicated the service not working. Any idea how to solve this?

**Comment by R33N4K0R** [comment]
add server key in your project

**Comment by curiousmit** [comment]
I already added the web api key given under project setting in firebase
console, as server key in the FCMNotificationBuilder Class, still the
service is not being called

**Comment by R33N4K0R** [comment]
not web api key use server key

**Comment by curiousmit** [comment]
where can i find that?

**Comment by R33N4K0R** [comment]
project setting second option cloud  messesing

**Comment by R33N4K0R** [comment]
get server key

**Comment by curiousmit** [comment]
ahhaa, i got that, let me update the server key and try running it

**Comment by R33N4K0R** [comment]
okay it will work

**Comment by curiousmit** [comment]
indeed it worked, thanks a tonne

**Comment by curiousmit** [comment]
The problem still persists as when the app is force closed from the app
drawer and after that if we send messages, no notification appears

**Comment by curiousmit** [comment]
If the app is in foreground or background, notification comes up, but if it
is removed from the background also, then notifications arent working.

**Comment by R33N4K0R** [comment]
in my case it works properly

**Comment by curiousmit** [comment]
is that so? Any idea what might be causing the problem?

**Comment by AndroidQQ** [comment]
where can i put the server key?

**Comment by lgnrvz** [comment]
Thanks

**Comment by lgnrvz** [comment]
To developer of this app, Thank you! And Great help!
