### ISSUE TITLE
Chat Messages do not display on the layout.

### ISSUE THREAD

**Issue by ZeppelinPower** [crazyhitty/firebase-chat#8]

**Comment by R33N4K0R** [comment]
is there messages in firebase database ?

**Comment by LedzZ123** [comment]
Yes my friend, Messages show in the Firebase DB, normally i think. Compiler keeps complaining about RecyclerAdapter, no adapter found, skipping layout. But i think i have connected the adapters correctly, and this error also appears in the UserListingFragment rendering, which works ok.

I look forward for new comments,
thank you for the quick replay.

Best Regards.

![messages](https://user-images.githubusercontent.com/31292050/29652909-56a1bad0-88b0-11e7-9ba3-2674abb27437.png)

**Comment by crazyhitty** [comment]
The reason this is happening is that no adapter is set to that recycler view. A new adapter will only be created when you receive some messages from the server. Can you debug this method in your application and check if data is being fetched properly or not.

https://github.com/crazyhitty/firebase-chat/blob/4c3c691cfbcd7a4ab930744a6b196984b33120f4/app/src/main/java/com/crazyhitty/chdev/ks/firebasechat/ui/fragments/ChatFragment.java#L142

**Comment by R33N4K0R** [comment]
i should suggest you to make  new project in firebase  , and use project's
.json file , maybe it will work for you .

R33N4

**Comment by LedzZ123** [comment]
@MintuReena I had already created a new project, and i am using its firebase google-services.json file. Still i thank you for the input.

@crazyhitty  My "onGetMessageSucess" is already implemented and looks like this  

`    @Override
    public void onReceiveMsgSuccess(ChatModel chatRoom) {
        if (chatRecyclerAdapter == null) {
            chatRecyclerAdapter = new ChatRecyclerAdapter(new ArrayList<ChatModel>());
            chatRecyclerView.setAdapter(chatRecyclerAdapter);
        }
        chatRecyclerAdapter.add(chatRoom);
        chatRecyclerView.smoothScrollToPosition(chatRecyclerAdapter.getItemCount() - 1);
    }` 
Which is called from ChatPresenter class that implements the ChatContract.View interface 

My "onGetMessageSuccess" on ChatPresenter
`    @Override
    public void onReceiveMessageSuccess(ChatModel chatRoom) {

        _view.onReceiveMsgSuccess(chatRoom);

    }`

Also this is my ChatInteractor 
`package com.example.ledzz.amc_app_1442355.Interactors;

import android.content.Context;


import com.example.ledzz.amc_app_1442355.Interfaces.Interfaces.Contracts.ChatContract;
import com.example.ledzz.amc_app_1442355.fcm.FcmNotificationBuilder;
import com.example.ledzz.amc_app_1442355.models.ChatModel;
import com.example.ledzz.amc_app_1442355.utils.Consts;
import com.example.ledzz.amc_app_1442355.utils.SharedPreferencesUtil;
import com.google.firebase.database.ChildEventListener;
import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseError;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import com.google.firebase.database.ValueEventListener;

public class ChatInteractor implements ChatContract.Interactor {

    private ChatContract.IncomingMessageListener _incomingMessageListener;
    private ChatContract.OutgoingMessageListener _outgoingMessageListener;


    public ChatInteractor(ChatContract.IncomingMessageListener incomingMessageListener) {

        this._incomingMessageListener = incomingMessageListener;

    }

    public ChatInteractor(ChatContract.OutgoingMessageListener _outgoingMessageListener) {

        this._outgoingMessageListener = _outgoingMessageListener;
    }

    public ChatInteractor(ChatContract.OutgoingMessageListener _outgoingMessageListener,
                          ChatContract.IncomingMessageListener _incomingMessageListener) {

        this._incomingMessageListener = _incomingMessageListener;
        this._outgoingMessageListener = _outgoingMessageListener;

    }

    /*
        End Of Constructors
    */


    @Override
    public void sendMessageToUser(final Context context, final ChatModel chatRoom, final String receiverFirebaseToken) {

        final String room1 = chatRoom.senderUid + "_" + chatRoom.receiverUid;
        final String room2 = chatRoom.receiverUid + "_" + chatRoom.senderUid;

        final DatabaseReference dbRef = FirebaseDatabase.getInstance().getReference();

        dbRef.child(Consts.ARG_CHAT_ROOMS).getRef().addListenerForSingleValueEvent(new ValueEventListener() {
            @Override
            public void onDataChange(DataSnapshot dataSnapshot) {

                if (dataSnapshot.hasChild(room1)) {

                    dbRef.child(Consts.ARG_CHAT_ROOMS).child(room1).
                            child(String.valueOf(chatRoom.timestamp)).setValue(chatRoom);

                } else if (dataSnapshot.hasChild(room2)) {

                    dbRef.child(Consts.ARG_CHAT_ROOMS).child(room2).
                            child(String.valueOf(chatRoom.timestamp)).setValue(chatRoom);

                } else {

                    dbRef.child(Consts.ARG_CHAT_ROOMS).child(room1).
                            child(String.valueOf(chatRoom.timestamp)).setValue(chatRoom);
                    receiveMessageFromUser(chatRoom.senderUid, chatRoom.receiverUid);

                }

                sendPushNotificationToReceiver(chatRoom.sender, chatRoom.message,
                        chatRoom.senderUid, new SharedPreferencesUtil(context)
                                .getPreferenceToString(Consts.ARG_FIREBASE_TOKEN),receiverFirebaseToken);
                _outgoingMessageListener.onSendMessageSuccess();

            }

            @Override
            public void onCancelled(DatabaseError databaseError) {

                _outgoingMessageListener.onSendMessageFail(Consts.SEND_MESSAGE_ERROR + databaseError.getMessage());

            }
        });
    }

    private void sendPushNotificationToReceiver(String username,
                                                String message,
                                                String uid,
                                                String firebaseToken,
                                                String receiverFirebaseToken) {
        FcmNotificationBuilder.initialize()
                .title(username)
                .message(message)
                .username(username)
                .uid(uid)
                .firebaseToken(firebaseToken)
                .receiverFirebaseToken(receiverFirebaseToken)
                .send();
    }

    @Override
    public void receiveMessageFromUser(String senderUID, String receiverUID) {

        final String room1 = senderUID + receiverUID;
        final String room2 = receiverUID + senderUID;

        final DatabaseReference dbRef = FirebaseDatabase.getInstance().getReference();

        dbRef.child(Consts.ARG_CHAT_ROOMS).getRef().addListenerForSingleValueEvent(new ValueEventListener() {

            @Override
            public void onDataChange(DataSnapshot dataSnapshot) {

                if (dataSnapshot.hasChild(room1)) {

                    dbRef.child(Consts.ARG_CHAT_ROOMS).child(room1).addChildEventListener(new ChildEventListener() {
                        @Override
                        public void onChildAdded(DataSnapshot dataSnapshot, String s) {

                            ChatModel chatRoom = dataSnapshot.getValue(ChatModel.class);
                            _incomingMessageListener.onReceiveMessageSuccess(chatRoom);

                        }

                        /*
                        Implementation for those methods not needed ---------
                         */
                        @Override
                        public void onChildChanged(DataSnapshot dataSnapshot, String s) {

                        }

                        @Override
                        public void onChildRemoved(DataSnapshot dataSnapshot) {

                        }

                        @Override
                        public void onChildMoved(DataSnapshot dataSnapshot, String s) {

                        }
                        /*
                        Implementation for those methods not needed ---------
                         */

                        @Override
                        public void onCancelled(DatabaseError databaseError) {
                            _incomingMessageListener.onReceiveMsgFail(Consts.RECEIVE_MESSAGE_ERROR + databaseError.getMessage());

                        }
                    });
                } else if (dataSnapshot.hasChild(room2)) {

                    FirebaseDatabase.getInstance()
                            .getReference()
                            .child(Consts.ARG_CHAT_ROOMS).child(room2).addChildEventListener(new ChildEventListener() {
                        @Override
                        public void onChildAdded(DataSnapshot dataSnapshot, String s) {

                            ChatModel chatRoom = dataSnapshot.getValue(ChatModel.class);
                            _incomingMessageListener.onReceiveMessageSuccess(chatRoom);

                        }

                        /*
                       Implementation for those methods not needed ---------
                        */
                        @Override
                        public void onChildChanged(DataSnapshot dataSnapshot, String s) {

                        }

                        @Override
                        public void onChildRemoved(DataSnapshot dataSnapshot) {

                        }

                        @Override
                        public void onChildMoved(DataSnapshot dataSnapshot, String s) {

                        }
                        /*
                        Implementation for those methods not needed ---------
                         */

                        @Override
                        public void onCancelled(DatabaseError databaseError) {

                            _incomingMessageListener.onReceiveMsgFail( Consts.RECEIVE_MESSAGE_ERROR + databaseError.getMessage());

                        }
                    });
                }
            }

            @Override
            public void onCancelled(DatabaseError databaseError) {

                _incomingMessageListener.onReceiveMsgFail(Consts.RECEIVE_MESSAGE_ERROR + databaseError.getMessage());

            }
        });

    }
}
`

If i have not missed anything i believe those are identical.  What could be the issue?

Thank you both for your inputs, and i am looking forward for new one :)

Best Regards

**Comment by LedzZ123** [comment]
The Comment Above was changed Completely

**Comment by ZeppelinPower** [comment]
Update: Problem was some method names not matching properly, so the listener could not work properly. Sry for the inconveniece yo may close this
